---
local_db: sqlite3:/var/vcap/services/couchdb/couchdb_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/couchdb/instances
ip_route: 127.0.0.1
logging:
  level: debug
pid: /var/vcap/sys/run/couchdb_node.pid
available_memory: 4096
max_memory: 128
node_id: couchdb_node_1
migration_nfs: /mnt/migration
couchdb:
  host: localhost
  port: 5984
  admin: admin
  adminpass: mysecretpassword
