---
host: 0.0.0.0
port: 29017

mongodb:
  host: 127.0.0.1      # 10.254.0.1
  port: 27017
  dbname: db
  user: test

filter:
  interval: 3          # seconds
  threshold: 0.9       # if disk usage percent equals or exceeds this value then block some operations

logging:
  level: info
  path: /tmp/mongodb_proxy/mongodb_proxy.log
