---
# cloud_controller_uri: api.vcap.me
service:
  name: elasticsearch
  version: "0.19.3"
  description: 'Elasticsearch search engine'
  plans: ['free']
  tags: ['elasticsearch', 'elasticsearch-0.19', 'search']
  timeout: 20
ip_route: localhost
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/elasticsearch_service.pid
node_timeout: 20
# allow_over_provisioning: false
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
