---
cloud_controller_uri: api.vcap.me
service:
  name: echo
  version: "1.0"
  description: 'Echo key-value store service'
  plans: ['free']
  tags: ['echo', 'echo-1.0', 'key-value', 'echobased']
ip_route: localhost
index: 0
token: changeechotoken
logging:
  level: debug
mbus: nats://nats:nats@192.168.202.134:4222
pid: /var/vcap/sys/run/echo_service.pid
node_timeout: 2
