source "http://rubygems.org"
gem 'bundler', '~> 1.0.10'
gem "sinatra"
gem "thin"
gem "nats", '>= 0.4.8'
gem 'yajl-ruby', '>= 0.8.1'
gem "em-http-request", "~> 1.0.0.beta.3"
gem "http_parser.rb",  :require => "http/parser"