---
#cloud_controller_uri: api.vcap.me
service:
  name: filesystem
  version: "0.1"
  description: 'Persistent filesystem service'
  plans: ['free']
  default_plan: free
  tags: []
#ip_route: 127.0.0.1
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/filesystem_service.pid
