---
service_name: mysql
snapshots_base_dir: /var/vcap/services/
serialization_base_dir: /var/vcap/services/
pid: /var/vcap/sys/run/mysql_worker.pid
# Temp directory to save uploaded file
tmp_dir: /tmp
resque:
  host: localhost
  port: 6379
  password: redis
  expire: 86400
index: 0
node_id: mysql_node_0
download_url_template: http://dl.vcap.me/serialized/#{service}/#{name}?token=#{token}
worker_count: 5
# addtional options
mysql:
  host: localhost
  port: 3306
  user: root
  pass: root
mysqldump_bin: mysqldump
gzip_bin: gzip
mysql_bin: mysql
