---
# cloud_controller_uri: api.vcap.me
service:
  name: neo4j
  version: "1.4"
  description: 'Neo4j NOSQL store'
  plans: ['free']
  tags: ['neo4j', 'neo4j-1.4', 'nosql']
host: localhost
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/neo4j_service.pid
node_timeout: 10
# allow_over_provisioning: false
