service_name: neo4j
backup_base_dir: /mnt/nfs/servicebackup/
# the following is for test purpose
local_db: sqlite3:/tmp/neo4j/neo4j_node.db
service_base_dir: /var/vcap/services/neo4j/instances/
log_level: DEBUG
fail_mail: figof@mozy.com

