---
cloud_controller_uri: http://api.vcap.me
service:
  name: memcached
  version: "1.4.13"
  description: 'Memcached high-performance, distributed memory object caching system'
  plans: ['free']
  tags: ['memcached', 'memcached-1.4.13', 'key-value', 'nosql']
ip_route: localhost
index: 0
token: changememcachedtoken
logging:
  level: debug
mbus: nats://localhost:4222/  
pid: /var/vcap/sys/run/memcached_service.pid
# allow_over_provisioning: false
# z_interval: 30
