---
local_db: sqlite3:/var/vcap/services/memcached/memcached_node.db
mbus: nats://localhost:4222/
index: 0
base_dir: /var/vcap/services/memcached/instances
logging:
  level: debug
pid: /var/vcap/sys/run/memcached_node.pid
capacity: 5
max_swap: 32
node_id: memcached_node_1
memcached_server_path: memcached
port_range:
  first: 11000
  last: 11050
migration_nfs: /mnt/appcloud
memcached_log_dir: /var/vcap/sys/log/memcached
command_rename_prefix: protect-command-prefix
max_clients: 500
memcached_timeout: 2

# z_interval: 30
# allow_over_provisioning: false
