---
# cloud_controller_uri: api.vcap.me
service:
  name: postgresql
  version: "9.0"
  description: 'PostgreSQL database service (vFabric)'
  plans: ['free']
  tags: ['postgresql', 'postgresql-9.0', 'relational']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/postgresql_service.pid
node_timeout: 2
# z_interval: 30
