---
service_name: postgresql
backup_base_dir: /tmp/backup/
backup_cmd: /var/vcap/packages/postgresql/bin/pg_dump --port=:port --host=:host --username=:user --file=:full_path/:name.sql :name
compress_cmd: /bin/gzip :full_path/:name.sql
node_id: postgresql_node_1
timeout: 120
postgresql:
  host: localhost
  port: 5432
  user: vcap
  pass: vcap
  database: postgres
logging:
  level: debug
pid: /var/vcap/sys/run/postgresql_backup.pid
