---
service_name: rabbit
snapshots_base_dir: /var/vcap/services/
serialization_base_dir: /var/vcap/services/
local_db: sqlite3:/var/vcap/services/rabbit/rabbit_node.db
script_name: /var/vcap/store/rabbitmq_common/bin
snapshot_quota: 5
# optional download tuning
serialization:
  max_download_size_mb: 10
  max_download_redirects: 5
# Temp directory to save uploaded file
tmp_dir: /tmp
resque:
  host: localhost
  port: 5454
index: 0
node_id: rabbit_node_free_1
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}
logging:
  level: debug
base_dir: /tmp/rabbitmq_instances
service_common_dir: /var/vcap/store/rabbitmq_common
service_log_dir: /var/vcap/sys/service-log/rabbit
image_dir: /tmp/rabbitmq_image
service_bin_dir:
  '2.4': /var/vcap/packages/rabbitmq-2.4
  '2.8': /var/vcap/packages/rabbitmq-2.8
  '3.0': /var/vcap/packages/rabbitmq-3.0
  erlang: /var/vcap/packages/erlang
