---
local_db: sqlite3:/var/vcap/services/blob/blob_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/blob/instances
ip_route: 127.0.0.1
logging:
  level: debug
pid: /var/vcap/sys/run/blob_node.pid
available_memory: 4096
max_memory: 128
meta_max_memory: 64
node_id: blob_node_1
nodejs_path : node
blobd_path: /var/vcap/packages/blob/bin/server.js
blobrestore_path: blobrestore
metad_path: mongod
metarestore_path: mongorestore
port_range:
  first: 45001
  last: 65000
migration_nfs: /mnt/migration
