---
# cloud_controller_uri: api.vcap.me
service:
  name: blob
  version: "0.2"
  description: 'Blob Gateway'
  plans: ['free']
  tags: ['blob', 'blob-0.2', 'nosql']
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
host: localhost
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
log_level: DEBUG
pid: /var/vcap/sys/run/blob_service.pid
# allow_over_provisioning: false
