---
#cloud_controller_uri: api.vcap.me
external_uri: service_broker.vcap.me
ip_route: localhost
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/service_broker.pid
local_db: sqlite3:/var/vcap/services/broker/service_broker.db
