source :rubygems

gem 'eventmachine', :git => 'git://github.com/cloudfoundry/eventmachine.git', :branch => 'release-0.12.11-cf'
gem "em-http-request"
gem "ruby-hmac"
gem "uuidtools"
gem "datamapper", "~> 1.1.0"
gem "dm-core", "= 1.1.0"
gem "do_sqlite3"
gem "dm-sqlite-adapter"
gem "sinatra", "~> 1.2.3"
gem "oauth"
gem "json", "~> 1.4.6"
gem "nats"

gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'git://github.com/cloudfoundry/vcap-common.git', :ref => 'b45f8e0af8'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'git://github.com/cloudfoundry/common.git', :ref => 'b96ec1192'
gem 'vcap_services_base', :git => 'git://github.com/cloudfoundry/vcap-services-base.git'
gem 'warden-client', :require => ['warden/client'], :git => 'git://github.com/cloudfoundry/warden.git'

group :test do
  #gem "webmock"
  gem "rake"
  gem "rack-test"
  gem "rspec"
  gem "simplecov"
  gem "simplecov-rcov"
  gem "ci_reporter"
end
