---
local_db: sqlite3:/var/vcap/services/rabbit/rabbit_node.db
base_dir: /var/vcap/services/rabbit/
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
ip_route: 127.0.0.1
available_memory: 4096
max_memory: 16
node_id: rabbit_node_1
pid: /var/vcap/sys/run/rabbit_node.pid
migration_nfs: /mnt/appcloud
max_clients: 500
port_range:
  first: 10001
  last: 20000
admin_port_range:
  first: 20001
  last: 30000
rabbitmq_server: rabbitmq-server
rabbitmq_log_dir: /var/vcap/sys/log/redis
# z_interval: 30
