service_name: mongodb
pid: /var/vcap/sys/run/mongodb_backup.pid
backup_base_dir: /mnt/nfs/servicebackup
local_db: sqlite3:/var/vcap/services/mongodb/mongodb_node.db
service_base_dir: /var/vcap/services/mongodb/instances/
mongod_log_dir: /var/vcap/sys/log/mongodb
mongodump_path:
  "1.8": "mongodump"

timeout: 600
logging:
  level: debug
