---
cloud_controller_uri: api.vcap.me
service:
  name: sqlfire
  version: "1.0"
  description: 'Sqlfire Distributed Database'
  plans: ['free', 'bronze', 'silver', 'gold']
  # Number of nodes to provision for each service instance.
  plan_mapping:
    free: 1
    bronze: 2
    silver: 3
    gold: 4
  tags: ['sqlfire', 'sqlfire-1.0', 'database']
  timeout: 40
ip_route: localhost
token: "0xdeadbeef"
mbus: nats://api.vcap.me:4222
logging:
  level: debug
pid: /var/vcap/sys/run/sqlfire_service.pid
# allow_over_provisioning: false

# Timeout for actual provisioning of the service
node_timeout: 40

#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
