---
local_db: sqlite3:/var/vcap/services/mvstore/mvstore_node.db
mbus: nats://nats:nats@172.16.228.158:4222/
index: 0
base_dir: /var/vcap/services/mvstore/instances
mvstore_log_dir: /var/vcap/services/mvstore/logs
pid: /var/vcap/sys/run/mvstore_node.pid
mvstore_restore_path: mvstore_restore
max_memory: 128
available_memory: 4096
node_id: mvstore_node_0
mvstore_path: /home/maxw/mvStore/server/bin/mvstored
port_range:
  first: 25001
  last: 45000
migration_nfs: /mnt/migration
logging:
  level: debug
