---
local_db: sqlite3:/var/vcap/services/mvstore/mvstore_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/mvstore/instances
mvstore_log_dir: /var/vcap/sys/log/mvstore
pid: /var/vcap/sys/run/mvstore_node.pid
max_memory: 128
available_memory: 4096
node_id: mvstore_node_0
mvstore_path: mvstored
port_range:
  first: 25001
  last: 45000
logging:
  level: debug
